version: 2
jobs:
  build:
    working_directory: ~/spring-boot-starter-pug4j
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew test jacocoTestReport coveralls
      # - save_cache:
      #     key: spring-boot-starter-pug4j-{{ checksum "build.gradle" }}
    